routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/clear-cache', function () {
    return Artisan::call('optimize:clear');
});


Route::group(['middleware' => 'guest', 'prefix' => 'admin'], function () {
    Route::any('/login', 'LoginController@index')->name('login');
    Route::post('main/checklogin', 'LoginController@checklogin')->name('checklogin');
});

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::get('/', 'DashboardController@index')->name('admin-home');
    Route::post('/', 'DashboardController@import_vehicle_master')->name('import_vehicle_master');
});

Route::group(['middleware' => 'auth', 'as' => 'admin.', 'prefix' => 'admin'], function () {
    Route::get('select_admin', 'DashboardController@select_admin');
    Route::get('/select_admin', function (Request $request) {
        // Retrieve a piece of data from the session...
        $value = session('key');
    
        // Specifying a default value...
        $value = session('key', 'default');
    
        // Store a piece of data in the session...
        session(['key' => $request->value]);
    });

    Route::resources([
        'age' => 'AgeController',
        'cubiccapacity' => 'CubicCapacityController',
        'seatcapacity' => 'SeatCapacityController',
        'weightcapacity' => 'WeightCapacityController',
        'idv' => 'IdvrateController',
        'price' => 'PriceController'
    ]);
    Route::get('idv-list/{category}', 'IdvrateController@master')->name('idv-list');
    Route::get('price-list/{category}', 'PriceController@master')->name('price-list');

    Route::resources([
        'slider' => 'SliderController',
        'tool' => 'ToolController',
        'type' => 'TypeController',
    ]);

    // Route::group(['prefix' => 'vehicle_wallet',], function () {
        Route::get('vw_vehicle/{id}', 'rtoadmin\VehicleController@detail')->name('vw_vehicledetail');
        Route::get('vw_setting', 'rtoadmin\SettingController@edit')->name('vw_editsetting');
        Route::post('vw_setting', 'rtoadmin\SettingController@update')->name('vw_updatesetting');
        Route::resources([
            'vw_slider'     => 'rtoadmin\SliderController',
            'vw_poster'     => 'rtoadmin\PosterController',
            'vw_category'   => 'rtoadmin\CategoryController',
            'vw_document'   => 'rtoadmin\DocumentController',
            'vw_article'    => 'rtoadmin\ArticleController',
            'vw_renew'      => 'rtoadmin\RenewController',
            'vw_otherapp'   => 'rtoadmin\OtherappController',
            'vw_page'       => 'rtoadmin\PageController',
            'vw_feedback'   => 'rtoadmin\FeedbackController',
            'vw_user'       => 'rtoadmin\UserController',
            'vw_vehicle'    => 'rtoadmin\VehicleController',
        ]);
    // });
    Route::resources([
        'company' => 'CompanyController',
        'healthzone' => 'HealthZoneController',
        'familysize' => 'FamilySizeController',
        'healthage' => 'HealthAgeController',
        'healthplan' => 'HealthPlanController',
        'healthplanprice' => 'HealthPlanPriceController',
    ]);
    Route::get('health/master', 'HealthPlanPriceController@master');

    Route::group(['prefix' => 'user'], function () {
        Route::get('/', 'UserController@list')->name('users-list');
        Route::get('/export', 'UserController@export')->name('users-export');
    });


    Route::group(['prefix' => 'profile'], function () {
        Route::get('/', 'LoginController@profile')->name('profile');
        Route::post('/', 'LoginController@edit_profile')->name('profile');
    });

    Route::group(['prefix' => 'setting'], function () {
        Route::get('/', 'SettingController@edit')->name('setting');
        Route::post('/', 'SettingController@update')->name('setting');
    });

    Route::post('ajex/changeoption', 'AjexController@changeoption')->name('ajex');
});

app/Models/Age.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Age extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function category()
    {
        return $this->hasOne('App\Models\Type', 'id', 'type_id');
    }
}

app/Http/Controllers/AgeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Age;
use App\Models\Type;
use Illuminate\Http\Request;

class AgeController extends Controller
{
    public function index()
    {

        $lists = Age::get();

        // set page and title -------------
        $page  = 'age.list';
        $title = 'Age list';
        $data  = compact('page', 'title', 'lists');

        return view('backend.layout.master', $data);
    }

    public function create()
    {
        $category = Type::get();
        $categoryArr  = ['' => 'Select Category'];
        if (!$category->isEmpty()) {
            foreach ($category as $pcat) {
                $categoryArr[$pcat->id] = $pcat->name;
            }
        }

        $page  = 'age.add';
        $title = 'Add Age';
        $data  = compact('page', 'title', 'categoryArr');

        return view('backend.layout.master', $data);
    }

    public function store(Request $request)
    {
        $rules = [
            'record'          => 'required|array',
            'record.age'      => 'required'
        ];

        $messages = [
            'record.age'  => 'Please Enter Age.',
        ];

        $request->validate($rules, $messages);

        $record           = new Age;
        $input            = $request->record;

        $record->fill($input);
        if ($record->save()) {
            return redirect(route('admin.age.index'))->with('success', 'Success! New record has been added.');
        } else {
            return redirect(route('admin.age.index'))->with('danger', 'Error! Something going wrong.');
        }
    }

    public function edit(Request $request, Age $age)
    {
        $editData =  ['record' => $age->toArray()];
        $request->replace($editData);
        $request->flash();

        $category = Type::get();
        $categoryArr  = ['' => 'Select Category'];
        if (!$category->isEmpty()) {
            foreach ($category as $pcat) {
                $categoryArr[$pcat->id] = $pcat->name;
            }
        }

        // set page and title ------------------
        $page = 'age.edit';
        $title = 'Edit Age';
        $data = compact('page', 'title', 'age', 'categoryArr');

        return view('backend.layout.master', $data);
    }

    public function update(Request $request, Age $age)
    {
        $rules = [
            'record'          => 'required|array',
            'record.age'      => 'required|numeric'
        ];
        $messages = [
            'record.age'  => 'Please Enter Age.'
        ];
        $request->validate($rules, $messages);

        $record           = Age::find($age->id);
        $input            = $request->record;
        $record->fill($input);

        if ($record->save()) {
            return redirect(route('admin.age.index'))->with('success', 'Success! Record has been edided');
        }
    }

    public function destroy(Age $age)
    {

        $age->delete();
        return redirect()->back()->with('success', 'Success! Record has been deleted');
    }
}

app/Http/Controllers/api/AgeController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use App\Models\Age;
use Illuminate\Http\Request;
use Validator;

class AgeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'type_id'  => 'required'
        ]);
        if ($validator->fails()) {
            $re = [
                'status'    => false,
                'message'   => 'Validations errors found.',
                'errors'    => $validator->errors()
            ];
        } else {
            $lists = Age::where('type_id', $request->type_id)->get();

            if ($lists->isEmpty()) {
                $re = [
                    'status' => false,
                    'message'    => 'No record(s) found.'
                ];
            } else {
                $re = [
                    'status' => true,
                    'message'    => $lists->count() . " records found.",
                    'data'   => $lists
                ];
            }
        }
        return response()->json($re);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Age  $age
     * @return \Illuminate\Http\Response
     */
    public function show(Age $age)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Age  $age
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Age $age)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Age  $age
     * @return \Illuminate\Http\Response
     */
    public function destroy(Age $age)
    {
        //
    }
}

resources/views/backend/inc/age/_form.blade.php
@if($message = Session::get('error'))
<div class="alert alert-danger alert-block">
  <button type="button" class="close" data-dismiss="alert">x</button>
  {{$message}}
</div>
@endif

@if(count($errors->all()))
<div class="alert alert-danger">
  <ul>
    @foreach($errors->all() as $error)
    <li>{{$error}}</li>
    @endforeach
  </ul>
</div>
@endif
<div class="row">
  <div class="col-lg-6">
    {{Form::text('record[age]', '', ['class' => 'squareInput', 'placeholder'=>'Enter age','required'=>'required'])}}
    {{Form::label('record[age]', 'Enter age'), ['class' => 'active']}}
  </div>

  <div class="col-lg-6">
    {{ Form::label('category', 'Select Category'), ['class' => 'active'] }}
    {{ Form::select('record[type_id]', $categoryArr,'0', ['class'=>'form-control squareInput', 'style'=> 'border:1px solid;','required'=>'required']) }}
  </div>
</div>

resources/views/backend/inc/age/add.blade.php
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Age Add</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="{{ route('admin-home') }}">
                                <i class="fas fa-home"></i> Home</a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="{{ route('admin.age.index') }}">Age</a>
                        </li>
                        <li class="breadcrumb-item active">Age Add</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="body">
                        <div class="header">
                            <h2 class="pt-2"><b>Age Add</b></h2>
                            <h2 class="header-dropdown m-r--5" style="top:10px;"><a href="{{ route('admin.age.index') }}" class="btn btn-primary" style="padding-top: 8px;">View Age</a></h2>
                        </div>
                        <hr>
                        <div class="formCard">
                            <div class="wrapper">
                                {{ Form::open(['url' => route('admin.age.store'), 'method'=>'POST', 'files' => true, 'class' => 'user']) }}
                                     @include('backend.inc.age._form')
                                  <div class="text-right">
                                    <input type="submit"class="btn btn-primary" name="save" value="Add"/>
                                  </div>
                                {{ Form::close() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/backend/inc/age/edit.blade.php
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Age Edit</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="{{ route('admin-home') }}">
                                <i class="fas fa-home"></i> Home</a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="{{ route('admin.age.index') }}">Age</a>
                        </li>
                        <li class="breadcrumb-item active">Age Edit</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="body">
                        <div class="header">
                            <h2 class="pt-2"><b>Age Edit</b></h2>
                            <h2 class="header-dropdown m-r--5" style="top:10px;"><a href="{{ route('admin.age.index') }}" class="btn btn-primary" style="padding-top: 8px;">View Age</a></h2>
                        </div>
                        <hr>
                        <div class="formCard">
                            <div class="wrapper">
                                {{ Form::open(['url' => route('admin.age.update',$age->id), 'method'=>'PUT','files' => true, 'class' => 'user']) }}
                                @include('backend.inc.age._form')
                                    <div class="text-right">
                                        <input type="submit"class="btn btn-primary" name="edit_age" value="Update"/>
                                    </div>
                                {{ Form::close() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/backend/inc/age/list.blade.php
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Age List</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="{{ route('admin-home') }}">
                                <i class="fas fa-home"></i> Home</a>
                        </li>
                        <li class="breadcrumb-item active">Age List</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2 class="pt-2"><b>Age List</b></h2>
                        <h2 class="header-dropdown m-r--5"><a href="{{ route('admin.age.create') }}" class="btn btn-primary" style="padding-top: 8px;">Add Age</a></h2>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example contact_list">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Age</th>
                                        <th>Category</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach($lists as $key => $list)
                                    @php
                                    $sn = $key + 1;
                                    @endphp
                                    <tr>
                                        <td>{{ $sn++ }}.</td>
                                        <td>{{ $list->age }}</td>
                                        <td>{{ $list->category->name }}</td>
                                        <td>
                                            <button class="btn tblActnBtn">
                                                <a href="{{ route('admin.age.edit',$list->id) }}" style="color: black;"><i class="material-icons">mode_edit</i></a>
                                            </button>
                                            {{ Form::open(array('url' => route('admin.age.destroy',$list->id), 'class' => 'btn tblActnBtn')) }}
                                            {{ Form::hidden('_method', 'DELETE') }}
                                            <button class="btn tblActnBtn">
                                                <a style="color: black;"><i class="material-icons">delete</i></a>
                                            </button>
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>