routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/clear-cache', function () {
    return Artisan::call('optimize:clear');
});


Route::group(['middleware' => 'guest', 'prefix' => 'admin'], function () {
    Route::any('/login', 'LoginController@index')->name('login');
    Route::post('main/checklogin', 'LoginController@checklogin')->name('checklogin');
});

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::get('/', 'DashboardController@index')->name('admin-home');
    Route::post('/', 'DashboardController@import_vehicle_master')->name('import_vehicle_master');
});

Route::group(['middleware' => 'auth', 'as' => 'admin.', 'prefix' => 'admin'], function () {
    Route::get('select_admin', 'DashboardController@select_admin');
    Route::get('/select_admin', function (Request $request) {
        // Retrieve a piece of data from the session...
        $value = session('key');
    
        // Specifying a default value...
        $value = session('key', 'default');
    
        // Store a piece of data in the session...
        session(['key' => $request->value]);
    });

    Route::resources([
        'age' => 'AgeController',
        'cubiccapacity' => 'CubicCapacityController',
        'seatcapacity' => 'SeatCapacityController',
        'weightcapacity' => 'WeightCapacityController',
        'idv' => 'IdvrateController',
        'price' => 'PriceController'
    ]);
    Route::get('idv-list/{category}', 'IdvrateController@master')->name('idv-list');
    Route::get('price-list/{category}', 'PriceController@master')->name('price-list');

    Route::resources([
        'slider' => 'SliderController',
        'tool' => 'ToolController',
        'type' => 'TypeController',
    ]);

    // Route::group(['prefix' => 'vehicle_wallet',], function () {
        Route::get('vw_vehicle/{id}', 'rtoadmin\VehicleController@detail')->name('vw_vehicledetail');
        Route::get('vw_setting', 'rtoadmin\SettingController@edit')->name('vw_editsetting');
        Route::post('vw_setting', 'rtoadmin\SettingController@update')->name('vw_updatesetting');
        Route::resources([
            'vw_slider'     => 'rtoadmin\SliderController',
            'vw_poster'     => 'rtoadmin\PosterController',
            'vw_category'   => 'rtoadmin\CategoryController',
            'vw_document'   => 'rtoadmin\DocumentController',
            'vw_article'    => 'rtoadmin\ArticleController',
            'vw_renew'      => 'rtoadmin\RenewController',
            'vw_otherapp'   => 'rtoadmin\OtherappController',
            'vw_page'       => 'rtoadmin\PageController',
            'vw_feedback'   => 'rtoadmin\FeedbackController',
            'vw_user'       => 'rtoadmin\UserController',
            'vw_vehicle'    => 'rtoadmin\VehicleController',
        ]);
    // });
    Route::resources([
        'company' => 'CompanyController',
        'healthzone' => 'HealthZoneController',
        'familysize' => 'FamilySizeController',
        'healthage' => 'HealthAgeController',
        'healthplan' => 'HealthPlanController',
        'healthplanprice' => 'HealthPlanPriceController',
    ]);
    Route::get('health/master', 'HealthPlanPriceController@master');

    Route::group(['prefix' => 'user'], function () {
        Route::get('/', 'UserController@list')->name('users-list');
        Route::get('/export', 'UserController@export')->name('users-export');
    });


    Route::group(['prefix' => 'profile'], function () {
        Route::get('/', 'LoginController@profile')->name('profile');
        Route::post('/', 'LoginController@edit_profile')->name('profile');
    });

    Route::group(['prefix' => 'setting'], function () {
        Route::get('/', 'SettingController@edit')->name('setting');
        Route::post('/', 'SettingController@update')->name('setting');
    });

    Route::post('ajex/changeoption', 'AjexController@changeoption')->name('ajex');
});

app/Models/Vwsetting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vwsetting extends Model
{
    use HasFactory;
}

resources/views/backend/inc/vw_setting/_form.blade.php
@if($message = Session::get('error'))
   <div class="alert alert-danger alert-block">
     <button type="button" class="close" data-dismiss="alert">x</button>
     {{$message}}
   </div>
@endif

@if(count($errors->all()))
    <div class="alert alert-danger">
      <ul>
        @foreach($errors->all() as $error)
          <li>{{$error}}</li>
        @endforeach
      </ul>
    </div>
@endif
<div class="row">
    <div class="col-lg-6">
        {{Form::text('title', '', ['class' => 'squareInput', 'placeholder'=>'Enter site name','required'=>'required'])}}
        {{Form::label('title', 'Enter site name'), ['class' => 'active']}}
    </div>
    <div class="col-lg-6">
        {{Form::text('tagline', '', ['class' => 'squareInput', 'placeholder'=>'Enter tagline','required'=>'required'])}}
        {{Form::label('tagline', 'Enter tagline'), ['class' => 'active']}}
    </div>
    <div class="col-lg-6">
        {{Form::text('mobile', '', ['class' => 'squareInput', 'placeholder'=>'Enter mobile number','required'=>'required'])}}
        {{Form::label('mobile', 'Enter mobile number'), ['class' => 'active']}}
    </div>
    <div class="col-lg-6">
        {{Form::text('email', '', ['class' => 'squareInput', 'placeholder'=>'Enter email','required'=>'required'])}}
        {{Form::label('email', 'Enter email'), ['class' => 'active']}}
    </div>
    <div class="col-lg-6">
        {{Form::file('logo',['class'=>'form-control squareInput'])}}
        {{Form::label('logo', 'Choose logo'), ['class' => 'active']}}
        <img src="{{ url('/').'/storage/'. $setting->logo }}" alt="" width="50" class="pt-4">
    </div>
    <div class="col-lg-6">
        {{Form::file('favicon',['class'=>'form-control squareInput'])}}
        {{Form::label('favicon', 'Choose favicon'), ['class' => 'active']}}
        <img src="{{ url('/').'/storage/'. $setting->favicon }}" alt="" width="50" class="pt-4">
    </div>
</div>

resources/views/backend/inc/vw_setting/add.blade.php
<!-- <section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Setting Add</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="{{ route('admin-home') }}">
                                <i class="fas fa-home"></i> Home</a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="{{ url(env('ADMIN_DIR').'/setting') }}">Setting</a>
                        </li>
                        <li class="breadcrumb-item active">Setting Add</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="body">
                        <div class="header">
                            <h2 class="pt-2"><b>Setting Add</b></h2>
                            <h2 class="header-dropdown m-r--5" style="top:10px;"><a href="{{ url(env('ADMIN_DIR').'/setting') }}" class="btn btn-primary" style="padding-top: 8px;">View Setting</a></h2>
                        </div>
                        <hr>
                        <div class="formCard">
                            <div class="wrapper">
                                {{ Form::open(['url' => url(env('ADMIN_DIR').'/setting/add'), 'method'=>'POST', 'files' => true, 'class' => 'user']) }}
                                     @include('backend.inc.setting._form')
                                  <div class="text-right">
                                    <input type="submit"class="btn btn-primary" name="save" value="Add"/>
                                  </div>
                                {{ Form::close() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



 -->

resources/views/backend/inc/vw_setting/edit.blade.php
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Setting</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="{{ route('admin-home') }}">
                                <i class="fas fa-home"></i> Home</a>
                        </li>
                        <li class="breadcrumb-item active">Setting Edit</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="body">
                        <div class="header">
                            <h2 class="pt-2"><b>Setting Edit</b></h2>
                            <!-- <h2 class="header-dropdown m-r--5" style="top:10px;"><a href="{{ url(env('ADMIN_DIR').'/setting') }}" class="btn btn-primary" style="padding-top: 8px;">View Setting</a></h2> -->
                        </div>
                        <hr>
                        <div class="formCard">
                            <div class="wrapper">
                                {{ Form::open(['url' => url( route('admin.vw_updatesetting') ), 'method'=>'POST','files' => true, 'class' => 'user']) }}
                                @include('backend.inc.vw_setting._form')
                                    <div class="text-right">
                                        <input type="submit"class="btn btn-primary" name="edit_setting" value="Update"/>
                                    </div>
                                {{ Form::close() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/backend/inc/vw_setting/list.blade.php
<!-- <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <ul class="breadcrumb breadcrumb-style ">
                            <li class="breadcrumb-item">
                                <h4 class="page-title">Color List</h4>
                            </li>
                            <li class="breadcrumb-item bcrumb-1">
                                <a href="{{ route('admin-home') }}">
                                    <i class="fas fa-home"></i> Home</a>
                            </li>
                            <li class="breadcrumb-item active">Color List</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="header">
                            <h2 class="pt-2"><b>Color List</b></h2>
                            <h2 class="header-dropdown m-r--5"><a href="{{ url(env('ADMIN_DIR').'/color/add') }}" class="btn btn-primary" style="padding-top: 8px;">Add Color</a></h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-hover js-basic-example contact_list">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Short Name</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php
                                        $sn = $lists->firstItem();
                                        @endphp
                                        @foreach($lists as $list)
                                        <tr>
                                            <td>{{ $sn++ }}</td>
                                            <td>{{ $list->name }}</td>
                                            <td>{{ $list->short_name }}</td>
                                            <td>
                                                <button class="btn tblActnBtn">
                                                    <a href="{{ url(env('ADMIN_DIR').'/color/edit/'.$list->id) }}" style="color: black;"><i class="material-icons">mode_edit</i></a>
                                                </button>
                                                <button class="btn tblActnBtn">
                                                    <a href="{{ url(env('ADMIN_DIR').'/color/delete/'.$list->id) }}" style="color: black;"><i class="material-icons">delete</i></a>
                                                </button>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
 -->