routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/clear-cache', function () {
    return Artisan::call('optimize:clear');
});


Route::group(['middleware' => 'guest', 'prefix' => 'admin'], function () {
    Route::any('/login', 'LoginController@index')->name('login');
    Route::post('main/checklogin', 'LoginController@checklogin')->name('checklogin');
});

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::get('/', 'DashboardController@index')->name('admin-home');
    Route::post('/', 'DashboardController@import_vehicle_master')->name('import_vehicle_master');
});

Route::group(['middleware' => 'auth', 'as' => 'admin.', 'prefix' => 'admin'], function () {
    Route::get('select_admin', 'DashboardController@select_admin');
    Route::get('/select_admin', function (Request $request) {
        // Retrieve a piece of data from the session...
        $value = session('key');
    
        // Specifying a default value...
        $value = session('key', 'default');
    
        // Store a piece of data in the session...
        session(['key' => $request->value]);
    });

    Route::resources([
        'age' => 'AgeController',
        'cubiccapacity' => 'CubicCapacityController',
        'seatcapacity' => 'SeatCapacityController',
        'weightcapacity' => 'WeightCapacityController',
        'idv' => 'IdvrateController',
        'price' => 'PriceController'
    ]);
    Route::get('idv-list/{category}', 'IdvrateController@master')->name('idv-list');
    Route::get('price-list/{category}', 'PriceController@master')->name('price-list');

    Route::resources([
        'slider' => 'SliderController',
        'tool' => 'ToolController',
        'type' => 'TypeController',
    ]);

    // Route::group(['prefix' => 'vehicle_wallet',], function () {
        Route::get('vw_vehicle/{id}', 'rtoadmin\VehicleController@detail')->name('vw_vehicledetail');
        Route::get('vw_setting', 'rtoadmin\SettingController@edit')->name('vw_editsetting');
        Route::post('vw_setting', 'rtoadmin\SettingController@update')->name('vw_updatesetting');
        Route::resources([
            'vw_slider'     => 'rtoadmin\SliderController',
            'vw_poster'     => 'rtoadmin\PosterController',
            'vw_category'   => 'rtoadmin\CategoryController',
            'vw_document'   => 'rtoadmin\DocumentController',
            'vw_article'    => 'rtoadmin\ArticleController',
            'vw_renew'      => 'rtoadmin\RenewController',
            'vw_otherapp'   => 'rtoadmin\OtherappController',
            'vw_page'       => 'rtoadmin\PageController',
            'vw_feedback'   => 'rtoadmin\FeedbackController',
            'vw_user'       => 'rtoadmin\UserController',
            'vw_vehicle'    => 'rtoadmin\VehicleController',
        ]);
    // });
    Route::resources([
        'company' => 'CompanyController',
        'healthzone' => 'HealthZoneController',
        'familysize' => 'FamilySizeController',
        'healthage' => 'HealthAgeController',
        'healthplan' => 'HealthPlanController',
        'healthplanprice' => 'HealthPlanPriceController',
    ]);
    Route::get('health/master', 'HealthPlanPriceController@master');

    Route::group(['prefix' => 'user'], function () {
        Route::get('/', 'UserController@list')->name('users-list');
        Route::get('/export', 'UserController@export')->name('users-export');
    });


    Route::group(['prefix' => 'profile'], function () {
        Route::get('/', 'LoginController@profile')->name('profile');
        Route::post('/', 'LoginController@edit_profile')->name('profile');
    });

    Route::group(['prefix' => 'setting'], function () {
        Route::get('/', 'SettingController@edit')->name('setting');
        Route::post('/', 'SettingController@update')->name('setting');
    });

    Route::post('ajex/changeoption', 'AjexController@changeoption')->name('ajex');
});

app/Models/Vwvehicle.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vwvehicle extends Model
{
    use HasFactory;

    // protected $with = ['vehicle_documents'];

    public function vehicle_documents()
    {
        return $this->hasMany('App\Models\Vwvehicledocument', 'vehicle_id', 'id');
        // return $this->belongsTo(Vwvehicle::class);
    }
    public function user()
    {
        return $this->belongsTo(Vwuser::class);
    }
    public function category()
    {
        return $this->belongsTo(Vwcategory::class);
    }
    // public function user()
    // {
    //     return $this->belongsTo(Vwuser::class);
    // }
    // public function category()
    // {
    //     return $this->belongsTo('App\Models\Vwcategory', 'category_id', 'id');
    // }
}

resources/views/backend/inc/vw_vehicle/detail.blade.php
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Vehicle Info</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="{{ route('admin-home') }}">
                                <i class="fas fa-home"></i> Home</a>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="{{ route('admin.vw_vehicle.index') }}">Vehicles</a>
                        </li>
                        <li class="breadcrumb-item active">Vehicle Info</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2 class="pt-2"><b>Vehicle Info</b></h2>
                        <!-- <h2 class="header-dropdown m-r--5"><a href="{{ route('admin.vw_feedback.create') }}" class="btn btn-primary" style="padding-top: 8px;">Add User</a></h2> -->
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example contact_list">
                                <tr>
                                    <th>Name</th>
                                    <td>{{ $list->user ? $list->user->first_name : ''}} {{ $list->user ? $list->user->last_name : ''}}</td>
                                    <th>Mobile</th>
                                    <td>{{ $list->user ? $list->user->mobile : ''}}</td>
                                </tr>
                                <tr>
                                    <th>Reg. Number</th>
                                    <td style="text-transform:uppercase">{{ $list->reg_number }}</td>
                                    <th>Category</th>
                                    <td>{{ $list->category ? $list->category->name : ''}}</td>
                                </tr>
                                
                            </table>
                            <div class="header ml-0 pl-0">
                                <h2 class="pt-2"><b>Vehicle Documents</b></h2>
                                <!-- <h2 class="header-dropdown m-r--5"><a href="{{ route('admin.vw_feedback.create') }}" class="btn btn-primary" style="padding-top: 8px;">Add User</a></h2> -->
                            </div>
                            <table class="table table-hover js-basic-example contact_list">
                                <tr>
                                    <th>Document</th>
                                    <th>Expiry Date</th>
                                    <th>image</th>
                                </tr>
                                @foreach($list->vehicle_documents as $vd)
                                <tr>
                                    
                                    <td style="text-transform:uppercase">{{$vd->document ? $vd->document->name : ''}}</td>
                                    <td>{{ $vd->expiry_date ?? 'NA' }}</td>
                                    <td class="table-img" style="width: 100px;">
                                        <a href="{{ url('/').'/storage/'. $vd->image }}" target="_blank">
                                            <img src="{{ url('/').'/storage/'. $vd->image }}" alt="">
                                        </a>
                                    </td>
                                </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/backend/inc/vw_vehicle/list.blade.php
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">User List</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="{{ route('admin-home') }}">
                                <i class="fas fa-home"></i> Home</a>
                        </li>
                        <li class="breadcrumb-item active">User List</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2 class="pt-2"><b>User List</b></h2>
                        <!-- <h2 class="header-dropdown m-r--5"><a href="{{ route('admin.vw_feedback.create') }}" class="btn btn-primary" style="padding-top: 8px;">Add User</a></h2> -->
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example contact_list">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>User</th>
                                        <th>Mobile</th>
                                        <th>Reg. Number</th>
                                        <th>Category</th>
                                        <th>Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                    $sn = 1;
                                    @endphp
                                    @foreach($lists as $list)
                                    <tr>
                                        <td>{{ $sn++ }}</td>
                                        <td>{{ $list->user ? $list->user->first_name : ''}} {{ $list->user ? $list->user->last_name : ''}}</td>
                                        <td>{{ $list->user ? $list->user->mobile : ''}}</td>
                                        <td style="text-transform:uppercase">{{ $list->reg_number }}</td>
                                        <td>{{ $list->category ? $list->category->name : '' }}</td>
                                        <td>{{ $list->created_at->format('d M Y') }}</td>
                                        <td>
                                            <button class="btn tblActnBtn">
                                                <a href="{{ route('admin.vw_vehicledetail',$list->id) }}" style="color: black;"><i class="material-icons">info</i></a>
                                            </button>
                                            <!-- <button class="btn tblActnBtn">
                                                <a href="{{ route('admin.vw_feedback.edit',$list->id) }}" style="color: black;"><i class="material-icons">mode_edit</i></a>
                                            </button> -->
                                            <!-- {{ Form::open(array('url' => route('admin.vw_feedback.destroy',$list->id), 'class' => 'btn tblActnBtn')) }}
                                            {{ Form::hidden('_method', 'DELETE') }}
                                            <button class="btn tblActnBtn">
                                                <a style="color: black;"><i class="material-icons">delete</i></a>
                                            </button>
                                            {{ Form::close() }} -->
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>